---
title: "Untitled"
author: "Yufei Liu"
date: "2024-05-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(caret)
library(stringr)
```

## R Markdown

```{r}
# 读取数据
setwd("~/Documents/Document/U.S/class/spring2024/Big Data/Final_project")
game <- read.csv("game2.csv")


game$series <- sapply(str_split(game$Title, "\\s+"), function(words) {
  paste(words[1:min(length(words), 2)], collapse = " ")
})

series_counts <- game %>%
  group_by(series, publisher) %>%
  summarise(Count = n(), .groups = 'drop')

game <- game %>%
  left_join(series_counts, by = c("series", "publisher"))

game <- game %>%
  mutate(IP_Type = case_when(
    Count >= 6 ~ "Big IP",
    Count >= 4 ~ "Medium IP",
    Count >= 2 ~ "Small IP",
    TRUE ~ "Not IP"
  ))

game <- game %>%
  filter(!is.na(activePlayers) & !is.na(genre) & !is.na(IP_Type))

game$IP_Type <- factor(game$IP_Type, levels = c("Big IP", "Medium IP", "Small IP", "Not IP"))

game <- game %>%
  drop_na(activePlayers, genre, IP_Type)

game$genre <- factor(game$genre)  # 将 genre 转换为因子
levels_genre <- levels(game$genre)

set.seed(123)
trainIndex <- createDataPartition(game$IP_Type, p = .8, 
                                  list = FALSE, 
                                  times = 1)
gameTrain <- game[ trainIndex,]
gameTest  <- game[-trainIndex,]

gameTrain$genre <- factor(gameTrain$genre, levels = levels_genre)
gameTest$genre <- factor(gameTest$genre, levels = levels_genre)

gameTrain_balanced <- upSample(x = gameTrain[, c("activePlayers", "genre")], y = gameTrain$IP_Type)

tree_model <- rpart(Class ~ activePlayers + genre, data = gameTrain_balanced, method = "class")

summary(tree_model)

# 绘制决策树
rpart.plot(tree_model, type = 3, extra = 101, fallen.leaves = TRUE, 
           main = "Decision Tree for IP Type by Active Players and Genre",
           cex = 0.4, 
           tweak = 1.2,
           box.palette = "RdBu", shadow.col = "gray", nn = TRUE)




```

```{}
```

```{r}
# Training set prediction
train_pred <- predict(tree_model, newdata = gameTrain, type = "class")

# Test set prediction
test_pred <- predict(tree_model, newdata = gameTest, type = "class")

# Calculating training set accuracy
train_accuracy <- mean(train_pred == gameTrain$IP_Type)
test_accuracy <- mean(test_pred == gameTest$IP_Type)

# Output results
print(paste("Training set accuracy:", train_accuracy))
print(paste("Test set accuracy:", test_accuracy))

# Calculating training set and test set R²
train_R2 <- caret::postResample(as.numeric(train_pred), as.numeric(gameTrain$IP_Type))["Rsquared"]
test_R2 <- caret::postResample(as.numeric(test_pred), as.numeric(gameTest$IP_Type))["Rsquared"]

# Output results
print(paste("Training set R²:", train_R2))
print(paste("Test set R²:", test_R2))
```
